### PR TITLE
Detection of MPEG4 v1

### PR DESCRIPTION
**Pull request by jonfryd**
Hi Adam,

Here's a quick PR for detecting MPEG4 v1 (used by e.g. GoPro cameras) via extra-mime-info.xml - including a couple of tests.

Seems like an oversight in the shared-mime-info DB. :)

### CODE REVIEW

**Comment by adamhooper** [comment]
Hi Jon,

First of all, thanks for the pull request!

I'm reticent to append to `extra-mime-info.xml` because it really ought to be upstream. So I've gone and created an upstream pull request: https://gitlab.freedesktop.org/xdg/shared-mime-info/merge_requests/14

I used your files exactly. Once this change is merged upstream, I'll pull it here and update the `mime-types` package. I'll also document what I did upstream, to streamline future feature requests like this one.

Thanks again!

**Comment by jonfryd** [comment]
Cool! 

Thanks for taking actions which benefit the entire open source community, Adam.

**Comment by adamhooper** [comment]
Status report: the change has been accepted upstream; I can fix this after shared-mime-info is updated upstream. There have been two releases in January, so it looks like the pace has picked up for that project.

@jonfryd Is there any urgency? Or shall I just wait for upstream to publish?

**Comment by jonfryd** [comment]
@adamhooper, thanks for the update!

No urgency really. We are running an inhouse build of `mime-types` right now which contains the change I suggested in `extra-mime-info.xml`. It gets the job done.

BTW, do you want me to remove the change in `extra-mime-info.xml` from this PR? I guess the tests are still useful when `shared-mime-info` 1.13 has been released. We could also close this PR? It's up to you.

**Comment by adamhooper** [comment]
No need to do anything. I like the PR; I'll merge after shared-mime-info 1.13 and nix the entry from extra-mime-info.xml afterwards.

**Comment by jonfryd** [comment]
Perfect. Thanks, @adamhooper.

**Comment by jonfryd** [comment]
Hi, @adamhooper.

Just a heads-up: I noticed [shared-mime-info 1.13.1](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/releases) was released recently.

Have a good day.

**Comment by adamhooper** [comment]
Thanks for the ping! I'm on it.

**Comment by adamhooper** [comment]
@jonfryd Thank you for your patience on this issue. I'm pleased with the end result: mime-types 0.1.3 incorporates your tests and works thanks to upstream shared-mime-info.

**Comment by jonfryd** [comment]
Brilliant! Wonderful stuff, @adamhooper.

**Pull request closed without merging**
